---
title: "Probability Theory"
---

```{r}
# Assignment 1
# Define the given values
probability_S <- 0.3
probability_not_S <- 0.7
conditional_probability_T_given_S <- 0.2
conditional_probability_T_given_not_S <- 0.6
conditional_probability_not_T_given_S <- 0.8
conditional_probability_not_T_given_not_S <- 0.4

# Calculate the probabilities
probability_T_and_S <- conditional_probability_T_given_S * probability_S
probability_T_and_not_s <- conditional_probability_T_given_not_S * probability_not_S
probability_not_T_and_S <- conditional_probability_not_T_given_S * probability_S
probability_not_T_and_not_S <- conditional_probability_not_T_given_not_S * probability_not_S
total_sum <- probability_T_and_S + probability_T_and_not_s + probability_not_T_and_S + probability_not_T_and_not_S

# Display the probabilities and the sum
cat("P(T ∩ S):",probability_T_and_S , "\n")
cat("P(T ∩ S'): ",probability_T_and_not_s, "\n")
cat("P(T' ∩ S): ",probability_not_T_and_S, "\n")
cat("P(T' ∩ S'): ",probability_not_T_and_not_S, "\n\n")
cat("Sum of all four probabilities:", total_sum, "\n")
```
```{r}
# Assignment 2
# Assuming you have the percentages
percentage_all_three <- 0.5
percentage_at_least_two <- 19.9
percentage_only_one <- 80.1

# Display the percentages
cat("Percentage of customers using all three devices:", percentage_all_three, "%\n")
cat("Percentage of customers using at least two devices:", percentage_at_least_two, "%\n")
cat("Percentage of customers using only one device:", percentage_only_one, "%\n")
```

```{r}
# Assignment 3
# Given probabilities
P_A <- 0.04
P_B_given_A <- 0.97
P_B_given_not_A <- 0.01

# Calculate complementary probability
P_not_A <- 1 - P_A

# Calculate total probability of triggering an alarm
P_B <- P_B_given_A * P_A + P_B_given_not_A * P_not_A

# Apply Bayes' theorem
P_not_A_given_B <- (P_B_given_not_A * P_not_A) / P_B
P_A_given_B <- (P_B_given_A * P_A) / P_B

# Display the results
cat("These results show that in case the alarm is triggered, there is a possibility of about", P_not_A_given_B * 100, "% that the product is flawless and a probability of about", P_A_given_B * 100, "% that the product is faulty.\n")
```