{
  "hash": "a5181fb255a5a679245e6eb7c896018a",
  "result": {
    "markdown": "---\ntitle: \"Directed Acyclic Graphs\"\n---\n\n::: {.cell hash='05_dag_cache/html/unnamed-chunk-1_bd60f06e0e219904326c85b58371e8bc'}\n\n```{.r .cell-code}\n#1\n# Load packages\nlibrary(dagitty)\nlibrary(ggdag)\n\n# create DAG from dagitty\ndag_model <- 'dag {\nbb=\"0,0,1,1\"\nD [exposure,pos=\"0.075,0.4\"]\nY [outcome,pos=\"0.4,0.4\"]\nL [pos=\"0.2,0.2\"]\nS [pos=\"0.3,0.5\"]\nD -> Y\nD -> L\nS -> D\nS -> Y\nL -> S\n}\n'\n\n# draw DAG\nggdag(dag_model) +\n  theme_dag() + # custom theme, can be left out\n  geom_dag_edges(edge_color = \"black\")\n```\n\n::: {.cell-output-display}\n![](05_dag_files/figure-html/unnamed-chunk-1-1.png){width=672}\n:::\n:::\n\nD represents the treatment variable (having parking spots),<br>\nY represents the outcome variable (sales),<br>\nL represents the location, and<br>\nS represents the store.<br>\n\n::: {.cell hash='05_dag_cache/html/unnamed-chunk-2_5b49e8666e889ac4c0d379ba75f57e6f'}\n\n```{.r .cell-code}\ndata <- readRDS(\"C:/Users/Anjali/Downloads/Causal_Data_Science_Data (1)/Causal_Data_Science_Data/customer_sat.rds\")\n\n#2.1\n#\nmodel1 <- lm(satisfaction ~ follow_ups, data = data)\nsummary(model1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> \n#> Call:\n#> lm(formula = satisfaction ~ follow_ups, data = data)\n#> \n#> Residuals:\n#>     Min      1Q  Median      3Q     Max \n#> -12.412  -5.257   1.733   4.506  12.588 \n#> \n#> Coefficients:\n#>             Estimate Std. Error t value Pr(>|t|)    \n#> (Intercept)  78.8860     4.2717  18.467 1.04e-10 ***\n#> follow_ups   -3.3093     0.6618  -5.001 0.000243 ***\n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n#> \n#> Residual standard error: 7.923 on 13 degrees of freedom\n#> Multiple R-squared:  0.658,\tAdjusted R-squared:  0.6316 \n#> F-statistic: 25.01 on 1 and 13 DF,  p-value: 0.0002427\n```\n:::\n:::\n\n::: {.cell hash='05_dag_cache/html/unnamed-chunk-3_b043e959e60f65c5a73fa39e28503926'}\n\n```{.r .cell-code}\n#2.2\n# Assuming 'subscription' is another column in your dataset\nmodel2 <- lm(satisfaction ~ follow_ups + subscription, data = data)\nsummary(model2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> \n#> Call:\n#> lm(formula = satisfaction ~ follow_ups + subscription, data = data)\n#> \n#> Residuals:\n#>     Min      1Q  Median      3Q     Max \n#> -4.3222 -2.1972  0.3167  2.2667  3.9944 \n#> \n#> Coefficients:\n#>                      Estimate Std. Error t value Pr(>|t|)    \n#> (Intercept)           26.7667     6.6804   4.007  0.00206 ** \n#> follow_ups             2.1944     0.7795   2.815  0.01682 *  \n#> subscriptionPremium   44.7222     5.6213   7.956 6.88e-06 ***\n#> subscriptionPremium+  18.0722     2.1659   8.344 4.37e-06 ***\n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n#> \n#> Residual standard error: 2.958 on 11 degrees of freedom\n#> Multiple R-squared:  0.9597,\tAdjusted R-squared:  0.9487 \n#> F-statistic: 87.21 on 3 and 11 DF,  p-value: 5.956e-08\n```\n:::\n:::\n\n3.\n**Model 1**:<br>\n**Coefficients**:<br>\nIntercept: 78.8860<br>\nFollow-ups: -3.3093<br>\n**Interpretation**:<br>\nThe intercept (78.8860) represents the estimated satisfaction when the number of follow-up calls is zero.<br>\nThe coefficient for follow-ups (-3.3093) suggests that, on average, for each additional follow-up call, satisfaction decreases by approximately 3.31 units.<br>\n**Statistical Significance**:<br>\nBoth intercept and follow-ups have p-values less than 0.05, indicating statistical significance.<br>\n**Model Fit**:<br>\nR²=0.658: Approximately 65.8% of the variability in satisfaction is explained by the number of follow-up calls.<br>\n<br>\n**Model 2**:<br>\n**Coefficients**:<br>\nIntercept: 26.7667<br>\nFollow-ups: 2.1944<br>\nSubscription Premium: 44.7222<br>\nSubscription Premium+: 18.0722<br>\n**Interpretation**:<br>\nThe intercept (26.7667) represents the estimated satisfaction when follow-up calls and all subscription variables are zero.<br>\nThe coefficient for follow-ups (2.1944) suggests that, on average, for each additional follow-up call, satisfaction increases by approximately 2.19 units.<br>\nThe coefficients for subscription levels indicate the change in satisfaction compared to the baseline (assumed to be subscription Starter).<br>\n**Statistical Significance**:<br>\nAll coefficients have p-values less than 0.05, indicating statistical significance.<br>\n**Model Fit**:<br>\nR² = 0.9597 : Approximately 95.97% of the variability in satisfaction is explained by follow-up calls and subscription levels.<br>\n<br>\nModel 2 provides a more comprehensive understanding of the factors influencing satisfaction as it includes both follow-up calls and subscription levels.<br>\nIn Model 2, the positive coefficient for follow-ups suggests that more follow-up calls are associated with higher satisfaction.<br>\nThe subscription coefficients in Model 2 indicate that, compared to the baseline (Starter), both Premium and Premium+ subscriptions are associated with higher satisfaction.<br>\nOverall, Model 2 suggests that, when accounting for subscription levels, both follow-up calls and subscription levels significantly contribute to explaining satisfaction. The high R² value in Model 2 indicates that the combination of follow-up calls and subscription levels explains a large portion of the variability in satisfaction\n\n\n::: {.cell hash='05_dag_cache/html/unnamed-chunk-4_c5987c02d80aaae91b83739d85982052'}\n\n```{.r .cell-code}\n#4\n# Assuming 'follow_ups', 'satisfaction', and 'subscription' are column names in dataset\nlibrary(dagitty)\nlibrary(ggdag)\n\n# Create a DAG model manually\ndag_model <- dagitty('dag {\n  follow_ups [exposure,pos=\"1,1\"]\n  satisfaction [outcome,pos=\"2,1\"]\n  subscription [pos=\"3,1\"]\n\n  subscription -> satisfaction\n  follow_ups -> satisfaction\n}')\n\n# plot adjustment sets\nggdag_adjustment_set(dag_model, shadow = T) +\n  theme_minimal() + # custom theme, can be left out\n  geom_dag_edges(edge_color = \"white\")\n```\n\n::: {.cell-output-display}\n![](05_dag_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\r\n<script src=\"../../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}